### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by tolenaki** [theahura/shoot-the-messenger#113] opened 2024-06-11 23:18 UTC
I am not tech or html savvy at all, all I know is it is not working, and so many of us just want to mass bulk UNSEND messages in fbk messenger (and IG) without notifying anyone, like a stealth ghost. Your app sounds like a dream, I wouldn't mind even paying for it, if it actually worked. Thank you so much!

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Logs**
Add logs from the chrome dev console. Hit f12 and go to the console tab in the window that pops up, and attach what you see there as a txt file.

**Comment by theahura** [comment] 2024-06-12 01:15
Thanks for the heads up. On it's own not super easy to figure out what the bug is here but I suspect it's the same as #112. Gonna close this as a duplicate of that one

**Closed by theahura** 2024-06-12 01:15 UTC
