### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by yourenotmadeoftuesday** [theahura/shoot-the-messenger#60] opened 2022-05-02 03:17 UTC
I downloaded this extension, and attempted to clear a chat. The box opened that said "remove messages, stop removal, buy me a coffee." However, when I clicked to remove the messages from the chat, the only thing that happened was that the pop up disappeared. 

I removed the extension from chrome and used chrome developer tools to load the unpacked extension. This time, when I went to remove messages, nothing happened and the pop up remained.

**Comment by theahura** [comment] 2022-05-02 03:27
hmm latest version works for me, and i believe the version on chrome webstore matches the version in dev right now so that shouldnt be any different. Can you send logs from the chrome dev console?

**Comment by yourenotmadeoftuesday** [comment] 2022-05-02 03:31
![Screenshot 2022-05-01 233053](https://user-images.githubusercontent.com/36829251/166181015-3636485e-b040-4284-8135-00463b320dae.png)

**Comment by theahura** [comment] 2022-05-02 03:33
Interesting...I've never seen that before. What is `100030611471986:1` -- are you sure thats the StM extension or is it some other extension? 

this is possibly related: https://stackoverflow.com/questions/54126343/how-to-fix-unchecked-runtime-lasterror-the-message-port-closed-before-a-respon

What version of chrome are you on?

**Comment by yourenotmadeoftuesday** [comment] 2022-05-02 03:35
My chrome version is: 101.0.4951.41 (Official Build) (64-bit) (cohort: 101_Win_41) 

That's definitely the StM extension. I've temporarily disabled other extensions to make sure nothing was interferring. 

I haven't seen that thread before, but I'll check it out!

**Comment by yourenotmadeoftuesday** [comment] 2022-05-02 03:38
Here's a new error I'm getting. I don't know if that will give you more information.

![image](https://user-images.githubusercontent.com/36829251/166181416-6e12c14b-5aa8-4411-9cd4-2dcac870a265.png)

**Comment by theahura** [comment] 2022-05-02 03:41
Chrome version could be the diff, im running 97.0.4692.99 on Linux :thinking: I have a windows machine lying around I can try to see if it works there.

That error is helpful, its saying that this line (https://github.com/theahura/shoot-the-messenger/blob/main/main.js#L104) isnt returning anything, which in turn means that this query (https://github.com/theahura/shoot-the-messenger/blob/main/main.js#L3) no longer points to the scroller. This is potentially an easy fix, but I'm curious why it doesn't work on my machine. Normally fb serves the same html and such across chrome versions/browsers/etc

Do you know enough JS/dev tools to figure out how to find the html element for the scroller? If you do, screenshotting that would help

**Comment by yourenotmadeoftuesday** [comment] 2022-05-02 03:45
I haven't touched JS since college, so I'm a little rusty.

Is this what you were looking for?
![image](https://user-images.githubusercontent.com/36829251/166181773-1ca11bb0-097d-4ddc-b755-1a44426cee6c.png)

**Comment by theahura** [comment] 2022-05-02 03:56
not quite. I'll dig into it on my end and get back to you, but im pretty busy this month so it may be a while. In the meantime though, if you'd like, you could try playing with the query I linked in the post above to see if you can find what html/css selectors are needed to find the scroller element

**Comment by yourenotmadeoftuesday** [comment] 2022-05-02 03:57
I appreciate it! Thanks for all the hard work you do!

**Comment by Auios** [comment] 2022-05-15 21:20
Any progress on this?

**Comment by theahura** [comment] 2022-05-15 21:24
Unfortunately no, I've been pretty slammed. I'll update my Twitter and this issue when I get around to it, but it's looking like June (my company has a lot of big events this month that were preparing for)

**Comment by Auios** [comment] 2022-05-16 19:34
Understandable.
In the mean time - I spent last night writing up my own janky ways to delete facebook messages in bulk. It's just searching the screen for pixel patterns and then moving the mouse and sending click events. It works but not very useful to people with different color themes/resolutions.
Anyone interested in helping is 100% welcome. I hope you don't mind me advertising my own solution here @theahura hehe! :)

https://github.com/Auios/Facebook-Message-Deleter

It would be cool to get some kind of vision implemented in this to be able to just identify message bubbles for any theme/color/resolution.

**Comment by theahura** [comment] 2022-06-05 21:20
Should work. Reopen this issue if it doesnt!

**Comment by yourenotmadeoftuesday** [comment] 2022-07-04 01:00
Good evening! I finally had a free evening to check out your update, but it's still having the same issue.

**Comment by theahura** [comment] 2022-07-04 05:39
You said you were using the development version above. Are you still? Can you confirm that you're on the latest version? (Check the manifest to see what it says)

**Comment by theahura** [comment] 2022-07-27 05:19
A few other people are seeing this issue so I'm going to have to take a deeper look. No promises on when I can get to it though, definitely not this weekend (moving apartments) so hopefully the next

**Comment by gamesguru** [comment] 2022-08-16 15:25
Getting the same on Chrome Version 104.0.5112.79 (Official Build) (64-bit).


```text
Got action:  REMOVE

main.js:249 Starting runner removal for N iterations:  25

main.js:251 Running count: 0

main.js:69 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'scrollTop')
    at getScroller (main.js:69:13)
    at prepareDOMForRemoval (main.js:111:3)
    at unsendAllVisibleMessages (main.js:140:36)
    at runner (main.js:252:29)
    at removeHandler (main.js:345:24)
    at main.js:423:9
```

**Comment by theahura** [comment] 2022-08-17 04:15
ok hoping to get to this next sunday (set aside time in my calendar and everything) will update you all soon

**Comment by theahura** [comment] 2022-08-29 04:26
Just pushed additional fixes such that everything works on my end. Closing this issue, but feel free to reopen it if things are broken still.

Special thanks to @zackradisic for a PR

**Comment by gamesguru** [comment] 2022-09-08 10:08
Is this supposedly fixed in `Version 5.2.0` ?

I received a super similar error. Using an incognito window.

```text
Got action:  REMOVE

main.js:257 Starting runner removal for N iterations:  10

main.js:259 Running count: 0

main.js:71 Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'scrollTop' in null
    at getScroller (main.js:71:24)
    at prepareDOMForRemoval (main.js:119:3)
    at unsendAllVisibleMessages (main.js:148:36)
    at runner (main.js:260:29)
    at removeHandler (main.js:362:24)
```

**Comment by theahura** [comment] 2022-09-08 15:19
It should be fixed -- I can successfully run this on my end with the latest version. That said, you're definitely using the latest code -- it's running 10 iterations instead of 25 which was changed in the 5.2 release :thinking: are you running off the chrome webstore? if yes, can you try packaging the github version and seeing if that works?

**Comment by gamesguru** [comment] 2022-09-09 02:45
I get exactly the same error. Possibly facebook is serving us different pages.

The extensions page also says this when loaded from source.

```text
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
```

**Comment by au-privateuser** [comment] 2022-09-13 01:28
Encountered the same issue as gamesguru

**Comment by theahura** [comment] 2022-09-13 17:14
A few misc possibilities:
- are you using english language messenger?
- are you on messenger.com?

can you run `document.querySelectorAll('[data-testid="message-container"]')` in the dev console and see if anything pops up? 

the error you are getting is here:
```
ROW_QUERY = '[data-testid="message-container"]';
...
function getScroller() {
  if (scroller) return scroller;
  let el = document.querySelector(ROW_QUERY);
  while (!('scrollTop' in el) || el.scrollTop === 0) {
    el = el.parentElement;
  }
  scroller = el;
  return el;
}
```
basically it's saying that `el` above is null, which in turn means the ROW_QUERY isn't working. You might be getting different pages from fb, so running the command above will validate if the ROW_QUERY is actually broken

**Comment by gamesguru** [comment] 2022-09-14 18:56
It seems to work, testing in the same Chrome. I got a `NodeList` with 4 `div` elements (I have 4 messages in the test conversation).

Perhaps not all have a `parentElement`? Just throwing things out there. Maybe we can run the loop inside the console and do a more real-world test?

**Comment by theahura** [comment] 2022-09-14 19:20
The error you're getting is very specific 🤔 can you post the full log when you try to delete the test conversation? Maybe what's happening is it finds the first few but then fails on a second iteration?

**Comment by theahura** [comment] 2022-09-14 19:22
We can also add a very loud consume

**Comment by gamesguru** [comment] 2022-09-14 21:11
That is the full log, it seems to fail on iteration 0. With the `'scrollTop' in el` statement.

I added `console.log(el);` and `console.log(el.parentElement);` statements before and inside the `while` loop.

It's starting with the `div` elements, but recursing all the way up to the root `<html>...</html>` element, before crashing... since the `parentElement` of the root is `null` and the `in` operator can't be applied.

Not sure why it is behaving differently for some of us, or what is the intended behavior of the `parentElement` accessor. But it definitely is acting up.

**Comment by theahura** [comment] 2022-09-15 06:22
Ooo that *is* interesting. Ok so what that block of code is trying to do is find the div that is used to scroll through the messages -- basically the parent container of all messages in the chain, the one that has 'overflow: scroll' set to it somewhere in the css. That's why we explicitly look for `scrollTop`: when you load a messenger chain, you load into the bottom, which means your div will have scrollTop == something greater than 0. Later we use that div to scroll up to load more messages.

But if you are in a brand new conversation with so few messages that there is *no* scroll bar, this error might pop up. Is that what is happening?

**Comment by gamesguru** [comment] 2022-09-15 15:42
Sounds about right. The conversation is only 4 messages in total.

**Comment by theahura** [comment] 2022-09-17 18:53
Does using STM work on larger message chains?

**Comment by au-privateuser** [comment] 2022-09-19 21:44
Tested on a larger message chain, confirming STM unspent messages successfully. 

Thanks

**Comment by gamesguru** [comment] 2022-09-22 16:09
> Does using STM work on larger message chains?

Sounds like it's a scrolling bug limited to small message chains. I emailed you, you can say hi on Facebook if you have it. We can test there.

W probably need to make some modification in the logic / code block you posted, around scrolling.

**Comment by theahura** [comment] 2022-10-07 01:03
I think it's worth creating a new issue if the small-message-removal problem is still extent. Closing this issue for now

Also @gamesguru I didn't get your email and I didnt see it in spam, but the easiest way to set up a test bed for the extension is to just message yourself

**Closed by theahura** 2022-10-07 01:03 UTC
