### ISSUE TITLE
Doesn't work 

### ISSUE THREAD

**Issue by notinterested1** [theahura/shoot-the-messenger#61] opened 2022-06-05 11:01 UTC
Chrome Version: 102.0.5005.63 (Official Build) (64-bit)
Microsoft Edge Version: 102.0.1245.33 (Official build) (64-bit)

It was working a weeks ago. But today it wasn't running.

**Comment by theahura** [comment] 2022-06-05 14:21
Duplicate of #60, will try to get this working today

**Closed by theahura** 2022-06-05 14:21 UTC
