### ISSUE TITLE
Messenger chat refreshes and scrolls down during extension operation.

### ISSUE THREAD

**Issue by LeonBrindley** [theahura/shoot-the-messenger#33] opened 2021-06-21 16:30 UTC
Hi, thanks for developing this extension by the way! 

Unfortunately with long message chains for me the plugin scrolls up, deletes a few messages, and then after a while the page refreshes and so it immediately jumps back to the bottom of the chain, before scrolling back up again. This additional scrolling means that it can't delete messages very quickly I'm afraid. Do you have any idea why this might be happening/have you encountered anything like this before?

Thanks!

**Comment by theahura** [comment] 2021-06-23 03:17
This is working as intended. 

The reason the application does this is because it turns out chrome and facebook and javascript and react are all very bad at dealing with memory from deleted HTML elements. Specifically, even if you delete an html element, a whole bunch of hanging JS references still exist for that element. So after some amount of time, chrome eventually hits a memory limit and the page crashes. 

To get around that issue, the extension refreshes every now and then. This clears the memory, allowing the deletion to continue. Unfortunately it does push the current removal back to the bottom, but hopefully since everything gets deleted it shouldnt be too long before it gets back to where it was previously. 

The old version of this extension used the Search in Conversation feature to hop to the last saved message on the refresh, thereby preventing the issue. Unfortunately, I can no longer trigger a search programmatically -- FB updated their code to prevent it.

Closing this out as WAI but feel free to reopen if you have other questions or issues.

**Comment by LeonBrindley** [comment] 2021-06-24 17:34
Hi! Thanks for replying. As it stands I'm trying to clear a rather long conversation, and the plugin scrolls to the top and tries to reach new messages, but then reloads before reaching them, and so I'm unable to delete them. It's having to scroll past lines which can't be deleted like nickname changes, polls, people joining the group etc. and whilst these are only individual lines, they seem to really add up. Is there a way for me to fix this issue and get the plug in working again, like stopping these grey update lines from showing up? Thanks! 👍

**Comment by theahura** [comment] 2021-06-24 18:54
Interesting. There's a few lines in the code (https://github.com/theahura/shoot-the-messenger/blob/main/main.js#L77) that should handle this. 

What version of the extension are you running? Can you email me screenshots/html dumps? I need to see the HTML selector tree for the elements that aren't being removed so I can check to see whether the hide function is misbehaving, or if these elements aren't being appropriately captured.

**Comment by LeonBrindley** [comment] 2021-06-24 20:20
I'm using the most recent version on GitHub, but I've tried the one on the Chrome Web Store also. How should I acquire the HTML dump (I've not done that much HTML before lol)?

**Comment by theahura** [comment] 2021-06-24 23:30
Easiest way to do it is to right click on whatever it is that you think should be hidden, and in the menu that pops up hit 'inspect element'. This should open another page called the chrome dev tools console, which will have a bunch of HTML in there. You can copy paste that whole thing, and even download it as a file. Whichever you do, just be aware that the contents of that file may include some of your messages so send with caution (and feel free to email me directly).

**Comment by LeonBrindley** [comment] 2021-07-04 14:40
It seems like the extension is currently failing to hide all elements with the data-scope of "messages_table", like poll announcements, nickname changes, theme changes, etc. There's now enough of them that the script fails to scroll up to where messages are currently present to delete them- has anyone else encountered this issue? 👍

**Comment by theahura** [comment] 2021-07-04 18:12
If I remember correctly, messages_table includes everything 🤔 so we don't necessarily want to hide all of those. 

Also, it occurs to me that for really long running messenger chains the fact that we can't delete those status bars means that *eventually* chrome will run out of memory. I don't think that's the issue you're running into @LeonBrindley, but it's something that I'm sure will pop up eventually.

**Comment by LeonBrindley** [comment] 2021-07-10 15:23
Interestingly, every so often when it refreshes it shows my profile picture where the messages would be along with the name 'Facebook user'. If that ever happens, then the extension stops working from that point onwards. Do you have any idea about how I can get the messages)table elements to be removed? Thanks!

**Comment by theahura** [comment] 2021-08-07 20:05
Can you try the latest version of this? I made a bunch of changes, hopefully it solves the problem.

**Closed** 2021-08-29 17:33 UTC
